# Generated by Django 3.0.2 on 2020-01-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.TextField(max_length=255)),
            ],
        ),
    ]
