# Generated by Django 3.0.2 on 2020-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
