# Generated by Django 3.0.2 on 2020-01-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200124_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
