# Generated by Django 3.0.2 on 2020-01-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFileName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
