# Generated by Django 3.0.2 on 2020-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200124_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefilename',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
